FROM golang:1.19.4 AS builder
WORKDIR /workdir
COPY main.go go.mod ./
RUN CGO_ENABLED=0 GOOS=linux go build -o app .

FROM alpine:3.17.0
COPY --from=builder /workdir/app /applications/app

ARG GID=1000
ARG UID=1000

RUN addgroup --system --gid $GID app \
  && adduser --system --ingroup app --uid $UID app

WORKDIR /applications
RUN chown -R app:app /applications
USER app

EXPOSE 8080
CMD ["./app"]