FROM node:24.20.0-alpine

ENV NODE_ENV=production
WORKDIR /app

ARG NPM_TOKEN

COPY package.json package-lock.json ./

RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc && \
    npm ci --omit=dev

RUN rm .npmrc

COPY app.js ./

EXPOSE 3000
CMD ["node", "app.js"]
