services:
  api:
    build:
      context: ./api
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
  web:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
