adminPassword: admin123
persistence:
  enabled: true
  size: 1Gi

ingress:
  enabled: true
  hosts:
    - grafana.127.0.0.1.nip.io
  # mkcert --key-file key.pem --cert-file cert.pem grafana.127.0.0.1.nip.io
  # k create secret tls grafana-tls --key key.pem --cert cert.pem
  tls: 
    - secretName: grafana-tls
      hosts:
        - grafana.127.0.0.1.nip.io
