name: "my-project" # opcjonalna nazwa projektu (domyślnie ustalana na podstawie nazwy folderu)
# version: "3.7" # pole raczej już nieużywane, wykorzystywane głownie dla wstecznej kompatybilności z Compose V1

services: # definicja kontenerów (odpowiednik docker container run)
  servicename1: # nazwa serwisu (np. elasticsearch), będzie to także DNS serwisu w sieci
    image: "my-first-image" # nazwa obrazu którego użyć do uruchomienia kontenera (opcjonalny w przypadku użycia build)
    environment: # zmienne środowiskowe przekazywane do kontenera przy jego uruchomieniu
      KEY: value
      KEY2: value2
      # - KEY=value
      # - KEY2=value2
    env_file: # zmienne środowiskowe z pliku
      - sample.env
    command: # nadpisanie domyślnego polecenia kontenera/obrazu
    volumes: # odpowiednik -v z docker run (wsparcie zarówno starszej jak i nowszej składni)
  servicename2: # kolejny serwis
    image: "my-second-image"

volumes: {}  # definicja wolumenu (docker volume create)

networks: {} # definicja sieci (docker network create)
